name: Build and push to MavenCentral
on:
  push:
    tags:
      - 1.*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3
        # v4.4.2
        with:
          validate-wrappers: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build release
        run: ./gradlew --configuration-cache javadoc publish -s -Pversion=${BUILD_LABEL//\//_}
        env:
          BUILD_LABEL: ${{ github.head_ref || github.ref_name }}

      - name: Upload and Release Bundle
        uses: jskov/action-nexus-publish@8145b6173999b6367355a220c2cd961f54e6b259
        # v1.2
        with:
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_token: ${{ secrets.OSSRH_TOKEN }}
          signing_key: ${{ secrets.SIGNING_KEY }}
          signing_key_secret: ${{ secrets.SIGNING_KEY_SECRET }}
          search_directory: build/dist
          target_action: 'promote_or_keep'
